files: ^src/.*\.py
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.20.4
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-merge-conflict
    - id: check-json
    - id: debug-statements
    - id: end-of-file-fixer
    - id: pretty-format-json
      args:
      - --autofix

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    - id: black
      language_version: python3
      args: ["-S"]
    # hooks to fix outdated syntaxes
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
    -   id: pyupgrade
        args:
        - --py38-plus

    # hooks to autosort imports
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

    # hooks to run flake8, run this last
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      exclude: ^lib/.*$|^tests/.*$
      language_version: python3
