files: ^src/.*\.py
repos:
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.37.0
- hooks:
  - id: end-of-file-fixer
  - id: check-merge-conflict
  - exclude: ^data/.*$
    id: check-json
  - id: check-yaml
  - id: debug-statements
  - exclude: ^docs/.*$
    id: end-of-file-fixer
  - args:
    - --autofix
    exclude: ^data/.*$
    id: pretty-format-json
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - args:
    - -S
    - --line-length=79
    id: black
    language_version: python3
  repo: https://github.com/psf/black
  rev: 22.10.0
- hooks:
  - args:
    - --py38-plus
    id: pyupgrade
  repo: https://github.com/asottile/pyupgrade
  rev: v3.2.0
- hooks:
  - args:
    - --profile
    - black
    - --filter-files
    id: isort
  repo: https://github.com/pycqa/isort
  rev: 5.10.1
- hooks:
  - args:
    - --max-line-length=120
    - --ignore=E203,W503
    id: flake8
  repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
