name: Dummy
on:
  push:
    branches:
      - develop
      - test/*

jobs:
  setenv:
    runs-on: ubuntu-latest
    steps:
      - name: match dev
        if: ${{ github.ref == 'refs/heads/develop' }}
        run: |
          echo "::set-output name=environment::dev"

      
    
  deploy:
    runs-on: ubuntu-latest
    needs: setenv
    steps:
      - name: echo
        run: |
          echo "environment=${{ env.environment }}"
          echo "github.ref=${{ github.ref }}"
          echo "github.head_ref=${{ github.head_ref }}"
          echo "environment=${{ env.environment }}"


