name: Dummy
on:
  push:
    branches:
      - develop
      - test/*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "github.ref=${{ github.ref }}"
          echo "GITHUB_REF=${{ GITHUB_REF }}"
